language: cpp
dist: focal
cache:
  ccache: true
  timeout: 600
  directories:
    - $HOME/Library/Caches/Homebrew
env:
  global:
    - CCACHE_COMPRESS=1
    - GCC_COLORS=\ 

os: linux
addons:
  apt:
    packages: [libboost-chrono-dev, libboost-date-time-dev, libboost-filesystem-dev, libboost-locale-dev,
        libboost-thread-dev, libboost-serialization-dev, libboost-program-options-dev, libboost-regex-dev,
        libboost-system-dev, libssl-dev, libevent-dev, libsodium-dev, libreadline-dev,
        libldns-dev, libgtest-dev, libhidapi-dev, libusb-1.0-0-dev, libudev-dev, python3, pkg-config, ccache]
  homebrew:
    update: true
    packages: [cmake, ccache, boost, openssl@1.1, libsodium, readline, ldns, hidapi, libusb, pkg-config]

jobs:
  include:
    - name: "focal"
    - name: "bionic"
      dist: bionic
    - name: "macOS 10.14"
      os: osx
      osx_image: xcode11.3.1
    - name: "Windows cross-compile"
      addons:
        apt:
          packages: [g++-mingw-w64-x86-64, python3]
      before_script:
        - export HOST=x86_64-w64-mingw32
        - sudo update-alternatives --set $HOST-g++ $(which $HOST-g++-posix)
        - sudo update-alternatives --set $HOST-gcc $(which $HOST-gcc-posix)
        - make -j2 -C contrib/depends HOST=$HOST
        - export CMAKE_OPTS="-DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/contrib/depends/$HOST/share/toolchain.cmake"
        - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/contrib/depends/$HOST/lib
  fast_finish: true
  allow_failures:
      - name: "Windows cross-compile"