// Copyright (c) 2026, The Arqma Network
//
// Planned Proof-of-Stake (Pulse-style) fork — scaffolding only.
// FORK_ACTIVE must remain false for mainnet production until the network votes go-live.
// Stagenet-only rehearsal: build with -DARQMA_STAGENET_POS_REHEARSAL=ON (see top-level CMakeLists.txt).
//
// Repository convention: all Git commit messages must be written in English.

#pragma once

#include <cstddef>
#include <cstdint>

#include "cryptonote_config.h"

#ifndef ARQMA_ANNOUNCE_PLANNED_POS_TRANSITION
/** Log a one-time notice about the planned PoS transition at daemon startup (before fork goes live). */
#define ARQMA_ANNOUNCE_PLANNED_POS_TRANSITION 1
#endif

namespace arqma::pulse_fork {

/** Mainnet / global go-live: keep false until governance schedules PoS on mainnet. */
inline constexpr bool FORK_ACTIVE = false;

#if defined(ARQMA_STAGENET_POS_REHEARSAL) && ARQMA_STAGENET_POS_REHEARSAL
inline constexpr bool STAGENET_POS_REHEARSAL_BUILD = true;
#else
inline constexpr bool STAGENET_POS_REHEARSAL_BUILD = false;
#endif

/**
 * Live PoS/Pulse rules for this process: global FORK_ACTIVE (future mainnet) OR stagenet-only rehearsal build
 * on STAGENET. MAINNET/TESTNET/FAKECHAIN never use the rehearsal branch — unchanged behaviour for public mainnet.
 */
inline bool fork_active(cryptonote::network_type net) noexcept
{
  if (FORK_ACTIVE)
    return true;
  if (STAGENET_POS_REHEARSAL_BUILD && net == cryptonote::STAGENET)
    return true;
  return false;
}

inline constexpr char HF_RELEASE_NAME[] = "ARQMA-V11.0.0-PoS";

/** Mainnet: last PoW-block height before PoS activates (exclusive PoW / inclusive first PoS per final spec). */
inline constexpr uint64_t MAINNET_FORK_HEIGHT_PLANNED = 2000000ULL;

/**
 * Stagenet: planned height = last scheduled HF height in stagenet_hard_forks[] + 100.
 * Keeps in sync — update STAGENET_LAST_HF_HEIGHT when adding rows above PoS fork in hardfork.cpp.
 */
inline constexpr uint64_t STAGENET_LAST_HF_HEIGHT = 220ULL;
inline constexpr uint64_t STAGENET_FORK_HEIGHT_PLANNED = STAGENET_LAST_HF_HEIGHT + 100ULL;

inline constexpr unsigned PULSE_TARGET_BLOCK_TIME_SEC = 60;
/** Oxen-style intra-block round slot size; used with convert_time_to_round and miner_fallback (255 rounds). */
inline constexpr unsigned PULSE_ROUND_TIMEOUT_SEC = 10;
/** Oxen-style clamp: r0 may shift within [prev+T−adj, prev+T+adj] around ideal schedule. */
inline constexpr unsigned PULSE_MAX_START_ADJUSTMENT_SEC = 5;
inline constexpr std::size_t PULSE_QUORUM_VALIDATORS_MIN = 10;
inline constexpr std::size_t PULSE_SIGNATURE_THRESHOLD = 7;

/**
 * Planned Pulse/PoS quorums reuse service-node operators; those nodes already require a running storage server that
 * calls arqmad's storage_server_ping (Arqma Pulse / SN pairing policy). Compatible stack: github.com ArqTras fork arqma-storage-server plus arqmad.
 */
inline constexpr bool POS_EXPECTS_STORAGE_SERVER_FOR_SERVICE_NODES = true;

/** Startup hint when this daemon acts as an SN operator (paired process for uptime proofs). */
inline constexpr char SN_POS_STORAGE_PAIRING_HINT[] =
    "PoS Pulse will expect the same pairing as today: keep arqma-storage-server (ArqTras fork) reachable and pinging "
    "this daemon's RPC (--arqmad-rpc-port in storage-server, sn_bind/storage port on daemon).";

/** Shown when RPC refuses PoW mining after the PoS fork (build with FORK_ACTIVE and/or HF >= network_version_20_pos). */
inline constexpr char POW_MINING_DISABLED_RPC_MESSAGE[] =
    "PoW mining is disabled after the PoS/Pulse fork — use PoS block production when available";

inline constexpr char NOTICE_LOG[] =
    "Planned HF ARQMA-V11.0.0-PoS (disabled in this build): "
    "\"Mining PoW is stop at block 2 m and blocks will be generated by PoS\" "
    "— mainnet transition height 2000000; stagenet rehearsal last_HF_height+100 (currently 320). "
    "PoS target block time 60s; quorum minimum 10 validators, signature threshold 7. "
    "Service-node Pulse quorum design follows the Arqma SN model: validators keep arqma-storage-server + arqmad paired.";

/*
 Next steps (from roadmap; incremental port in progress):
 - Wire format: pulse_header + reward + sn_winner_tail (header varints) + pulse_validator_signatures on block when major_version >= network_version_20_pos (see cryptonote_basic.h, crypto::hash4); JSON via json_object (block dump / RPC tooling).
 - Pulse round scheduling, producer selection, and signer tooling (daemon validates quorum signatures when FORK_ACTIVE).
 - Extend arqnet Pulse (**`pulse_proposal`** / **`pulse_vote`** relay and round state**) beyond point-to-point validate-only paths.
 - When FORK_ACTIVE + HF >= v20, cumulative difficulty uses next_difficulty_pulse_pos (60s LWMA) instead of DIFFICULTY_TARGET_V16. Governance / dev / net coinbase outputs (mainnet GOV_/DEV_/NET_WALLET_ADDRESS) stay on the HF16+ path in construct_miner_tx — do not strip for Pulse without a coordinated consensus + validation change.
 - PoW skip when FORK_ACTIVE + block major_version >= network_version_20_pos; quorum signatures are enforced by verify_pulse_fork_block_rules from service_node_list::block_added / alt_block_added (oxen-core style: after DB accept, in the SNL hook), not alongside PoW skipping.
 - Stagenet/mocknet rehearsal; then uncomment HF rows in hardfork.cpp with real timestamps.
 - Finalize Arqma quorum crypto + Pulse producer scheduling; tighten storage/arqnet liveness checks for validators if spec requires.
 - Optional: checkpoint relay expansion, wallet/RPC alignment, HF_VERSION_PULSE_POS in cryptonote_config.h
 - Coinbase: Pulse header `reward` is the full miner_tx total (miner + SN + gov + dev + net); last three vouts remain gov/dev/net for hf >= 16.
*/

inline constexpr uint64_t planned_fork_height_for_net(cryptonote::network_type net)
{
  switch (net)
  {
    case cryptonote::MAINNET:
      return MAINNET_FORK_HEIGHT_PLANNED;
    case cryptonote::STAGENET:
      return STAGENET_FORK_HEIGHT_PLANNED;
    default:
      return 0;
  }
}

/**
 * When true, PoW block templates must not be produced and mining must not run.
 * Activated if the block being built is already on the PoS major version, or if
 * `fork_active(net)` and height is at/after the planned fork height for that network (stagenet rehearsal uses the same height metadata).
 */
inline bool pow_mining_disabled_for_chain(cryptonote::network_type net,
    uint8_t block_major_version_for_next_block,
    uint64_t next_block_height)
{
  if (block_major_version_for_next_block >= cryptonote::network_version_20_pos)
    return true;

  if (!fork_active(net))
    return false;

  const uint64_t fh = planned_fork_height_for_net(net);
  if (fh == 0)
    return false;

  return next_block_height >= fh;
}

} // namespace arqma::pulse_fork
