// Copyright (c) 2026, The Arqma Network
//
// Planned Proof-of-Stake (Pulse-style) fork — scaffolding only.
// FORK_ACTIVE must remain false until full consensus + network code is merged.
//
// Repository convention: all Git commit messages must be written in English.

#pragma once

#include <cstddef>
#include <cstdint>

#include "cryptonote_config.h"

#ifndef ARQMA_ANNOUNCE_PLANNED_POS_TRANSITION
/** Log a one-time notice about the planned PoS transition at daemon startup (before fork goes live). */
#define ARQMA_ANNOUNCE_PLANNED_POS_TRANSITION 1
#endif

namespace arqma::pulse_fork {

/** Master switch — keep false until PoS validation and block production are implemented. */
inline constexpr bool FORK_ACTIVE = false;

inline constexpr char HF_RELEASE_NAME[] = "ARQMA-V11.0.0-PoS";

/** Mainnet: last PoW-block height before PoS activates (exclusive PoW / inclusive first PoS per final spec). */
inline constexpr uint64_t MAINNET_FORK_HEIGHT_PLANNED = 2000000ULL;

/**
 * Stagenet: planned height = last scheduled HF height in stagenet_hard_forks[] + 100.
 * Keeps in sync — update STAGENET_LAST_HF_HEIGHT when adding rows above PoS fork in hardfork.cpp.
 */
inline constexpr uint64_t STAGENET_LAST_HF_HEIGHT = 220ULL;
inline constexpr uint64_t STAGENET_FORK_HEIGHT_PLANNED = STAGENET_LAST_HF_HEIGHT + 100ULL;

inline constexpr unsigned PULSE_TARGET_BLOCK_TIME_SEC = 60;
inline constexpr std::size_t PULSE_QUORUM_VALIDATORS_MIN = 10;
inline constexpr std::size_t PULSE_SIGNATURE_THRESHOLD = 7;

/** Shown when RPC refuses PoW mining after the PoS fork (build with FORK_ACTIVE and/or HF >= network_version_20_pos). */
inline constexpr char POW_MINING_DISABLED_RPC_MESSAGE[] =
    "PoW mining is disabled after the PoS/Pulse fork — use PoS block production when available";

inline constexpr char NOTICE_LOG[] =
    "Planned HF ARQMA-V11.0.0-PoS (disabled in this build): "
    "\"Mining PoW is stop at block 2 m and blocks will be generated by PoS\" "
    "— mainnet transition height 2000000; stagenet rehearsal last_HF_height+100 (currently 320). "
    "PoS target block time 60s; quorum minimum 10 validators, signature threshold 7.";

/*
 Next steps (from roadmap; not implemented here):
 - Pulse round scheduling, producer selection, validator signatures (7-of-10).
 - Extend arqnet or adopt OxenMQ-style transport for Pulse messages.
 - Post-fork: coinbase/miner_tx layout for SN rewards only; replace LWMA difficulty (next_difficulty_v16) with Pulse rules when FORK_ACTIVE.
 - PoW skip is wired in blockchain.cpp for major_version >= network_version_20_pos when FORK_ACTIVE (must add quorum/signature verification before any release).
 - Stagenet/mocknet rehearsal; then uncomment HF rows in hardfork.cpp with real timestamps.
 - Optional: checkpoint relay expansion, wallet/RPC alignment, HF_VERSION_PULSE_POS in cryptonote_config.h
*/

inline constexpr uint64_t planned_fork_height_for_net(cryptonote::network_type net)
{
  switch (net)
  {
    case cryptonote::MAINNET:
      return MAINNET_FORK_HEIGHT_PLANNED;
    case cryptonote::STAGENET:
      return STAGENET_FORK_HEIGHT_PLANNED;
    default:
      return 0;
  }
}

/**
 * When true, PoW block templates must not be produced and mining must not run.
 * Activated if the block being built is already on the PoS major version, or if
 * FORK_ACTIVE and height is at/after the planned mainnet/stagenet fork height (for rehearsal builds).
 */
inline bool pow_mining_disabled_for_chain(cryptonote::network_type net,
    uint8_t block_major_version_for_next_block,
    uint64_t next_block_height)
{
  if (block_major_version_for_next_block >= cryptonote::network_version_20_pos)
    return true;

  if (!FORK_ACTIVE)
    return false;

  const uint64_t fh = planned_fork_height_for_net(net);
  if (fh == 0)
    return false;

  return next_block_height >= fh;
}

} // namespace arqma::pulse_fork
