// Copyright (c) 2026, The Arqma Network
//
// Planned Proof-of-Stake (Pulse-style) fork — scaffolding only.
// FORK_ACTIVE must remain false until full consensus + network code is merged.

#pragma once

#include <cstddef>
#include <cstdint>

#ifndef ARQMA_ANNOUNCE_PLANNED_POS_TRANSITION
/** Log a one-time notice about the planned PoS transition at daemon startup (before fork goes live). */
#define ARQMA_ANNOUNCE_PLANNED_POS_TRANSITION 1
#endif

namespace arqma::pulse_fork {

/** Master switch — keep false until PoS validation and block production are implemented. */
inline constexpr bool FORK_ACTIVE = false;

inline constexpr char HF_RELEASE_NAME[] = "ARQMA-V11.0.0-PoS";

/** Mainnet: last PoW-block height before PoS activates (exclusive PoW / inclusive first PoS per final spec). */
inline constexpr uint64_t MAINNET_FORK_HEIGHT_PLANNED = 2000000ULL;

/**
 * Stagenet: planned height = last scheduled HF height in stagenet_hard_forks[] + 100.
 * Keeps in sync — update STAGENET_LAST_HF_HEIGHT when adding rows above PoS fork in hardfork.cpp.
 */
inline constexpr uint64_t STAGENET_LAST_HF_HEIGHT = 220ULL;
inline constexpr uint64_t STAGENET_FORK_HEIGHT_PLANNED = STAGENET_LAST_HF_HEIGHT + 100ULL;

inline constexpr unsigned PULSE_TARGET_BLOCK_TIME_SEC = 60;
inline constexpr std::size_t PULSE_QUORUM_VALIDATORS_MIN = 10;
inline constexpr std::size_t PULSE_SIGNATURE_THRESHOLD = 7;

inline constexpr char MINING_STOP_USER_MESSAGE[] =
    "Mining PoW is stop at block 2 m and blocks will be generated by PoS";

inline constexpr char NOTICE_LOG[] =
    "Planned HF ARQMA-V11.0.0-PoS (disabled in this build): "
    "\"Mining PoW is stop at block 2 m and blocks will be generated by PoS\" "
    "— mainnet transition height 2000000; stagenet rehearsal last_HF_height+100 (currently 320). "
    "PoS target block time 60s; quorum minimum 10 validators, signature threshold 7.";

/*
 Next steps (from roadmap; not implemented here):
 - Pulse round scheduling, producer selection, validator signatures (7-of-10).
 - Extend arqnet or adopt OxenMQ-style transport for Pulse messages.
 - Post-fork: skip PoW checks; coinbase/miner_tx layout for SN rewards only.
 - Stagenet/mocknet rehearsal; then uncomment HF rows in hardfork.cpp with real timestamps.
 - Optional: checkpoint relay expansion, wallet/RPC alignment, HF_VERSION_PULSE_POS in cryptonote_config.h
*/

} // namespace arqma::pulse_fork
